name:                curl-runnings
version:             0.16.4
github:              aviaviavi/curl-runnings
license:             MIT
author:              Avi Press
maintainer:          mail@avi.press
copyright:           2020 Avi Press
category:            Testing
synopsis:            A framework for declaratively writing curl based API tests

extra-source-files:
- README.md
- examples/*

description:         Please see the README on Github at <https://github.com/aviaviavi/curl-runnings#readme>

dependencies:
- base >= 4.0 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Testing.CurlRunnings
  - Testing.CurlRunnings.Types
  - Testing.CurlRunnings.Internal
  - Testing.CurlRunnings.Internal.Parser
  - Testing.CurlRunnings.Internal.Headers
  - Testing.CurlRunnings.Internal.KeyValuePairs
  - Testing.CurlRunnings.Internal.Payload
  dependencies:
  - aeson >=1.2.4.0 && <2.0
  - bytestring >=0.10.8.2
  - case-insensitive >=0.2.1
  - base64-bytestring >=1.0.0.2
  - clock >=0.7.2
  - dhall >=1.8.2
  - dhall-json >= 1.0.9
  - directory >=1.3.0.2
  - hashable >= 1.2.7.0
  - hspec >=2.4.4
  - hspec-expectations >=0.8.2
  - http-conduit >=2.3.6
  - megaparsec >=7.0.4
  - connection >=0.2.8
  - http-client-tls >=0.3.5.3
  - http-types >=0.12.3
  - pretty-simple >=2.0.2.1
  - regex-posix >=0.95.2
  - text >=1.2.2.2
  - time >=1.8.0.2
  - transformers >=0.5.2.0
  - unordered-containers >=0.2.8.0
  - vector >=0.12.0
  - yaml >=0.8.28

executables:
  curl-runnings:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >=4.7
    - cmdargs >=0.10.20
    - directory >=1.3.0.2
    - aeson >=1.2.4.0 && <2.0
    - http-conduit >=2.2.4
    - bytestring >=0.10.8.2
    - curl-runnings
    - tar >=0.5.0.3
    - text >=1.2.2.2
    - zlib >=0.6.1.2

tests:
  curl-runnings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring >=0.10.8.2
    - curl-runnings
    - directory >=1.3.0.2
    - aeson >=1.2.4.0 && <2.0
    - hspec >= 2.4.4
    - hspec-expectations >=0.8.2
    - raw-strings-qq >= 1.1
    - text >=1.2.2.2
